# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PSOD_Lipschitz_constraint1 <- function(n, m) {
    .Call(`_OAPB_PSOD_Lipschitz_constraint1`, n, m)
}

PSOD_Finite_qnorm_1_constraint1 <- function(X, m) {
    .Call(`_OAPB_PSOD_Finite_qnorm_1_constraint1`, X, m)
}

PSOD_Finite_qnorm_inf_constraint1 <- function(k, x) {
    .Call(`_OAPB_PSOD_Finite_qnorm_inf_constraint1`, k, x)
}

